### ISSUE TITLE
add "expertice" field under name

### ISSUE THREAD

**Issue by Mjanssen03** [Renovamen/oh-my-cv#10]
Hi there, 

Is it possible to have a option to put the expertise of a individual onder the name? This would allow for a clear demonstration of the expertise in one glance.

Something like this, or another implementation?

---
name: Haha Ha
Expertise: Engineer X
header:
  - text: <span class="iconify" data-icon="tabler:phone"></span> (+1) 123-456-7890
  - text: <span class="iconify" data-icon="tabler:mail"></span> renovamenzxh@gmail.com
    link: mailto:renovamenzxh@gmail.com
  - text: <span class="iconify" data-icon="tabler:brand-github"></span> Renovamen
    link: https://github.com/Renovamen
  - text: <span class="iconify" data-icon="tabler:brand-linkedin"></span> xiaohan-zou
    link: https://www.linkedin.com/in/xiaohan-zou/
  - text: <span class="iconify" data-icon="charm:person"></span> zxh.io
    link: https://zxh.io
  - text: <span class="iconify" data-icon="ic:outline-location-on"></span> 1234 Abc Street, Boston, MA 02215
    newLine: true
---

Thanks for making a great tool!

**Comment by Vuccappella** [comment]
I second this, its crucial to be able to put at the top the position you are an expert in or the position you are applying for as it makes the job for recruiters much easier at a glance to be able to tell who for what position is applying

**Comment by Renovamen** [comment]
Does this work for you?

<img width="1218" alt="image" src="https://github.com/Renovamen/oh-my-cv/assets/29454156/8a502824-e3a2-498a-be38-24f65adcae2b">

(To add a colon `:` in the header, you need to use a [YAML safe notation](https://www.ascii-code.com/character/:) for a it (like `&colon;`) instead of directly using `:`)

**Comment by Mjanssen03** [comment]
Thank you for the possible solution.
However I thought about adding it under the HAha HA section in blue in a bigger font then the one used in header. Like there is a name and header field, could there also be a field for expertise?

**Comment by Renovamen** [comment]
I see. Does this work for you? Use HTML strings:

<img width="1220" alt="image" src="https://github.com/Renovamen/oh-my-cv/assets/29454156/854719c9-48e3-4f75-912d-8fc758d702bd">

And I just found that using [YAML multi-line strings](https://yaml-multiline.info/) allows you to directly use special symbols like `:` and `#`, which is more convenient.

This solution might not be very intuitive, and I understand the importance of adding an expertise field. However, I want the header customization to be more flexible. We might find many other fields to add to the header in the future, and it doesn’t make much sense to add all of them individually.

**Comment by Mjanssen03** [comment]
Thank you for your quick response!
This solution will work for me. 
Good luck with the project!
