### ISSUE TITLE
Using Standard Computer Fonts

### ISSUE THREAD

**Issue by Vuccappella** [Renovamen/oh-my-cv#14]
I think the idea behind making a markdown CV is it should be simple and easy yet somewhat flxible.

the problem with the tool right now is you can use only google fonts, so the most popular fonts, especially for CV's - Times New Roman. Arial, Helvetica,Calibri etc. are actually not available, this causes several problems:

1. You can't have an actually simple CV that uses a font available on ALL computers using google fonts
2. You can't use the tried and true classic fonts used since decades in your CV, the best you can do is find a look-a-like in google fonts
3. Google fonts has A LOT of fonts and picking the right one for your CV is hard and confusing, a lot of the fonts are actually not suitable for a CV so this extra choice just adds non-needed complexity. 

My suggestion is at the very least to add classic fonts like Arial,Times New Roman,Calibri, Helvetica etc. to the dropdown and make one of them them be the default.

As a workaround in css on the heading you can specify font-family: Arial, Helvetica, sans-serif;  and over write the google fonts but this has to be tested better.

**Comment by Renovamen** [comment]
Thanks for the suggestion. It looks like there's a pr https://github.com/Renovamen/oh-my-cv/pull/12 already attempting this. I’ll look into it.

**Comment by Renovamen** [comment]
This should be resolved by pr https://github.com/Renovamen/oh-my-cv/pull/12. I'll add font-family fallbacks later.
