### ISSUE TITLE
"Heads Up!" warning appears in output PDF

### ISSUE THREAD

**Issue by RUSRUSHB** [Renovamen/oh-my-cv#21]
After clicking export PDF, the "Heads Up!" warning appears:
![Screenshot 2024-07-09 175810](https://github.com/Renovamen/oh-my-cv/assets/50075926/33c5a0b1-a2e4-40f6-ae66-a4a548f6b873)

and it is also in the output PDF:
![Screenshot 2024-07-09 175602](https://github.com/Renovamen/oh-my-cv/assets/50075926/01b88b4b-61c3-44c3-8447-80e8e05633ad)

**Comment by Renovamen** [comment]
Hi, thanks for letting me know. I've explicitly hidden the popup when printing. However, I haven't encountered this issue on my browsers, so I can't test if it works. So could you please check the new version and see if it's fixed? If not, could you tell me which browser you're using? Thanks!

**Comment by RUSRUSHB** [comment]
Yes, it is fixed now. Thanks!
For your reference, here is the information of my browser: Microsoft Edge 版本 126.0.2592.87 (正式版本) (64 位)
