### ISSUE TITLE
CV does not fit in the 'Export PDF' option.

### ISSUE THREAD

**Issue by greenned** [Renovamen/oh-my-cv#3]
It's a super nice and lightweight app.  Thank you.

However, when i tried to export PDF. the CV on the print pop-up is different from the web display.
It's smaller.  Can you please fix it ?

my environments are
- macos Sonoma 14.0
- Chrome (not work in Safari as well)

<img width="934" alt="스크린샷 2023-10-05 오후 11 33 29" src="https://github.com/Renovamen/oh-my-cv/assets/42107709/3e9e5d18-f0d9-4043-b2fe-744c201170f8">

**Comment by Renovamen** [comment]
Hi, thanks for letting me know! I'm aware of this issue, which only appeared after a recent Chrome update. As a workaround, adjusting the "scale" to around 150% in the Chrome print popup seems to work. Unfortunately, I haven't discovered a method to fundamentally solve it yet, but I'll keep up with it and explore alternative fixes.

**Comment by greenned** [comment]
Thanks for the reply. I believe the issue may be related to the default page size being set to A3 instead of A4. I apologize for not providing more details initially.

**Comment by vinaysudani** [comment]
Faced the same issue on Windows 10 and Chrome Version 118.0.5993.118 (Official Build) (64-bit)
Setting "scale" to 150% while saving the pdf worked fine. Thanks for workaround @Renovamen

**Comment by Renovamen** [comment]
Hi, it seems like after a recent upgrade of Chrome (I'm using 119.0.6045.123 (Official Build) (arm64)), this issue has disappeared. So I will close this issue. If you still encounter this problem, please let me know, and I'll reopen it. Thanks!
